// src/components/Roadmap.tsx
import React, { useState, useEffect } from "react"
import { useIntl } from "react-intl"
import styled from "styled-components"
import axios from "axios"

import Translation from "./Translation"
import Link from "./Link"
import { FakeLinkExternal, CardItem as Item } from "./SharedStyledComponents"

import { translateMessageId } from "../utils/translations"

import { GATSBY_FUNCTIONS_PATH } from "../constants"

const Section = styled.div`
  display: flex;
  flex-wrap: wrap;
  margin-top: 2rem;
  margin-bottom: 2rem;
  width: 100%;
`

const ErrorMsg = styled.div`
  color: ${(props) => props.theme.colors.fail};
`

export interface Label {
  name: string
}

export interface Issue {
  html_url?: string
  title: string
  errorMsg?: string
  labels: Array<Label>
  state?: string
  user?: {
    login: string
  }
  pull_request?: string
}

export interface IPropsIssueSection {
  issues: Array<Issue>
}

const IssueSection: React.FC<IPropsIssueSection> = ({ issues }) => {
  if (!issues) {
    return null
  }
  return (
    <Section>
      {issues.map((issue, idx) => {
        const url = issue.html_url ? issue.html_url : "#"
        return (
          <Item to={url} key={idx} hideArrow={true}>
            <div>{issue.title}</div>
            {issue.errorMsg && <ErrorMsg>{issue.errorMsg}</ErrorMsg>}
            <div>
              {issue.html_url && <FakeLinkExternal>Discuss</FakeLinkExternal>}
            </div>
          </Item>
        )
      })}
    </Section>
  )
}

export interface IProps {}

const Roadmap: React.FC<IProps> = () => {
  const intl = useIntl()
  const issue: Issue = {
    title: translateMessageId("loading", intl),
    labels: [],
  }
  const blankIssues: Array<Issue> = Array(6).fill(issue)
  const [issues, setIssues] = useState<{ [status: string]: Array<Issue> }>({
    inProgress: blankIssues,
    planned: blankIssues,
    implemented: blankIssues,
  })

  // Checks if any of the label objects in the array of labels associated with an issue have the spam label
  const issueIsSpam = (issue: Issue) =>
    issue.labels.some((label) => label.name === "Type: Spam")

  const issueIsAbandoned = (issue: Issue) =>
    issue.labels.some((label) => label.name === "Status: Abandoned")

  // TODO update to pull PRs & issues separately
  useEffect(() => {
    axios
      .get(`${GATSBY_FUNCTIONS_PATH}/roadmap`)
      .then((response) => {
        let issues: Array<Issue> = []
        if (response.data && response.data.data) {
          issues = response.data.data
          const planned = issues
            .filter((issue) => {
              for (const label of issue.labels) {
                if (label.name === "Status: Up Next") {
                  return issue.state === "open"
                }
              }
              return false
            })
            .slice(0, 6)

          const inProgress = issues
            .filter((issue) => {
              // if is an open PR
              if (!!issue.pull_request) {
                return issue.state === "open"
              }

              // if issue is in progress
              for (const label of issue.labels) {
                if (label.name === "Status: In Progress") {
                  return issue.state === "open"
                }
              }
              return false
            })
            .slice(0, 6)

          const implemented = issues
            .filter(
              (issue) =>
                issue.state === "closed" &&
                !!issue.user &&
                "allcontributors[bot]" !== issue.user.login &&
                !!issue.pull_request &&
                !issueIsSpam(issue) &&
                !issueIsAbandoned(issue)
            )
            .slice(0, 6)
          setIssues({
            planned,
            inProgress,
            implemented,
          })
        }
      })
      .catch((error) => {
        console.error(error)
        const errorIssue: Issue = {
          title: translateMessageId("loading-error", intl),
          errorMsg: translateMessageId("refresh", intl),
          labels: [],
        }
        const errorIssues: Array<Issue> = Array(3).fill(errorIssue)
        setIssues({
          planned: errorIssues,
          inProgress: errorIssues,
          implemented: errorIssues,
        })
      })
  }, [intl])

  return (
    <div>
      <p>
        <Translation id="page-about-p-1" />
      </p>
      <p>
        <Link to="https://github.com/ethereum/ethereum-org-website/blob/master/LICENSE">
          <Translation id="page-about-link-1" />
        </Link>
        .
      </p>
      <p>
        <Translation id="page-about-p-2" />{" "}
        <Link to="https://github.com/ethereum/ethereum-org-website">
          <Translation id="page-about-link-2" />
        </Link>
        <Translation id="page-about-p-3" />
      </p>
      <ul>
        <li>
          <Translation id="page-about-li-1" />
        </li>
        <li>
          <Translation id="page-about-li-2" />
        </li>
        <li>
          <Translation id="page-about-li-3" />
        </li>
      </ul>
      <p>
        <Translation id="page-about-p-4" />
      </p>
      <h3>
        <Translation id="page-about-h3" />
      </h3>
      <p>
        <Translation id="page-about-p-5" />{" "}
        <Link to="https://github.com/ethereum/ethereum-org-website/labels/Status%3A%20In%20Progress">
          <Translation id="page-about-link-3" />{" "}
        </Link>
        .
      </p>
      <IssueSection issues={issues.inProgress} />
      <h3>
        <Translation id="page-about-h3-2" />
      </h3>
      <p>
        <Translation id="page-about-p-6" />{" "}
        <Link to="https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aissue+is%3Aopen+label%3A%22Status%3A+Up+Next%22">
          <Translation id="page-about-link-3" />
        </Link>
        .
      </p>
      <IssueSection issues={issues.planned} />
      <h3>
        <Translation id="page-about-h3-1" />
      </h3>
      <p>
        <Translation id="page-about-p-7" />{" "}
        <Link to="https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aissue+is%3Aclosed">
          <Translation id="page-about-link-6" />{" "}
        </Link>
        .
      </p>
      <IssueSection issues={issues.implemented} />
      <h2>
        <Translation id="page-about-h2" />
      </h2>
      <p>
        <Translation id="page-about-p-8" />
      </p>
      <ul>
        <li>
          <Link to="https://discord.gg/bTCfS8C">
            <Translation id="page-about-link-4" />
          </Link>
        </li>
        <li>
          <Link to="https://github.com/ethereum/ethereum-org-website/issues/new/choose">
            <Translation id="page-about-link-7" />
          </Link>
        </li>
        <li>
          <Link to="https://twitter.com/ethdotorg">
            <Translation id="page-about-link-5" />
          </Link>
        </li>
      </ul>
    </div>
  )
}

export default Roadmap

// docs/.vuepress/components/Roadmap.vue
<template>
  <div>
    <h2 class="l2">Request a feature</h2>
    Do you have an idea for how to improve ethereum.org?
    <ul>
      <li>
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://github.com/ethereum/ethereum-org-website/issues/new/choose"
        >
          Create an issue on Github</a
        >
      </li>
      <li>
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://twitter.com/ethdotorg"
        >
          Reach out to us on Twitter</a
        >
      </li>
    </ul>
    <h2 class="l2">Ethereum.org Roadmap</h2>
    <p>
      Ever since the launch of ethereum.org, we strive to be transparent about
      how we operate. This is one of our core values, as we believe transparency
      is crucial to Ethereum's success. The
      <a
        target="_blank"
        rel="noopener noreferrer"
        href="https://github.com/ethereum/ethereum-org-website/blob/master/LICENSE"
      >
        source code of this repository is licensed under the MIT License</a
      >.
    </p>
    <p>
      We use
      <a
        target="_blank"
        rel="noopener noreferrer"
        href="https://github.com/ethereum/ethereum-org-website"
      >
        GitHub</a
      >
      as our primary project management tool. We organize our tasks in 3
      categories; in progress, planned and implemented. We do our best to keep
      the community informed what the status is of a specific task.
    </p>

    <h3 class="l3">Work in progress</h3>
    <p>
      Tasks that we're implementing.
      <a
        target="_blank"
        rel="noopener noreferrer"
        href="https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aissue+is%3Aopen+label%3A%22Status%3A+In+Progress%22"
      >
        View the full list of tasks in progress on Github </a
      >.
    </p>
    <div class="flex flex-wrap m-0 mt-2 mb-2">
      <div
        class="issue-item w-100 ma-1 pt-1 pb-1 pr-1 pl-1 border-box-shadow-hover hide-icon"
        v-for="issue in inProgress"
        :key="issue.number"
      >
        <div class="l4 mb-2">{{ issue.title }}</div>

        <div v-if="issue.errorMsg" class="issue-content">
          <div>{{ issue.errorMsg }}</div>
        </div>
        <div v-else class="issue-content">
          <div>Task #{{ issue.number }}</div>
          <a :href="issue.html_url" target="_blank" rel="noopener noreferrer">
            Discuss
          </a>
        </div>
      </div>
    </div>

    <h3 class="l3">Planned features</h3>
    <p>
      Tasks we've queued up to implement next.
      <a
        target="_blank"
        rel="noopener noreferrer"
        href="https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aissue+is%3Aopen+label%3A%22Status%3A+Up+Next%22"
      >
        View the full list of planned tasks on Github </a
      >.
    </p>
    <div class="flex flex-wrap m-0 mt-2 mb-2">
      <div
        class="issue-item w-100 ma-1 pt-1 pb-1 pr-1 pl-1 border-box-shadow-hover hide-icon"
        v-for="issue in planned"
        :key="issue.number"
      >
        <div class="l4 mb-2">{{ issue.title }}</div>

        <div v-if="issue.errorMsg" class="issue-content">
          <div>{{ issue.errorMsg }}</div>
        </div>
        <div v-else class="issue-content">
          <div>Task #{{ issue.number }}</div>
          <a :href="issue.html_url" target="_blank" rel="noopener noreferrer">
            Discuss
          </a>
        </div>
      </div>
    </div>
    <h3 class="l3">Implemented features</h3>
    <p>
      Recently completed tasks.
      <a
        target="_blank"
        rel="noopener noreferrer"
        href="https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aissue+is%3Aclosed"
      >
        View the full list of implemented tasks on Github </a
      >.
    </p>

    <div class="flex flex-wrap m-0 mt-2 mb-2">
      <div
        class="issue-item w-100 ma-1 pt-1 pb-1 pr-1 pl-1 border-box-shadow-hover hide-icon"
        v-for="issue in implemented"
        :key="issue.number"
      >
        <div class="l4 mb-2">{{ issue.title }}</div>

        <div v-if="issue.errorMsg" class="issue-content">
          <div>{{ issue.errorMsg }}</div>
        </div>
        <div v-else class="issue-content">
          <div>Task #{{ issue.number }}</div>
          <a :href="issue.html_url" target="_blank" rel="noopener noreferrer">
            Discuss
          </a>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { translations } from '../theme/utils/translations'
const axios = require('axios')

export default {
  data() {
    const issue = {
      title: 'Loading...'
    }
    const issues = Array(6).fill(issue)
    return {
      inProgress: issues,
      planned: issues,
      implemented: issues
    }
  },

  mounted() {
    axios
      .get('/.netlify/functions/roadmap')
      .then(response => {
        let issues = []
        if (response.data && response.data.data) {
          issues = response.data.data
          this.inProgress = issues
            .filter(issue => {
              // if is an open PR
              if (!!issue.pull_request && issue.state === 'open') {
                return true
              }

              // if issue is in progress
              for (const label of issue.labels) {
                if (label.name === 'Status: In Progress') {
                  return true
                }
              }
              return false
            })
            .slice(0, 6)

          this.planned = issues
            .filter(issue => {
              for (const label of issue.labels) {
                if (label.name === 'Status: Up Next') {
                  return true
                }
              }
            })
            .slice(0, 6)

          this.implemented = issues
            .filter(issue => {
              return (
                issue.state === 'closed' &&
                'allcontributors[bot]' !== issue.user.login
              )
            })
            .slice(0, 6)
        }
      })
      .catch(error => {
        const errorIssue = {
          title: 'Loading error.',
          errorMsg: 'Please refresh the page.'
        }
        const errorIssues = Array(3).fill(errorIssue)
        this.inProgress = errorIssues
        this.planned = errorIssues
        this.implemented = errorIssues
      })
  }
}
</script>

<style lang="stylus" scoped>
@import '../theme/styles/config.styl';

// TODO use Card component vs. these styles
.issue-item
  flex 0 1 260px
  list-style none
  border-radius .5rem
  width 100%

  display: flex
  flex-direction: column
  justify-content: space-between

  & > h3:before
    display none

.issue-content
  display: flex
  justify-content: space-between

#wrapper.dark-mode
  .issue-item
    &:hover
      border 1px dotted $colorPrimaryDark500

@media (max-width: $breakXS)
  .issue-item
    margin 0
    margin-top 1rem
    flex 1 1 260px
</style>
