// src/components/TranslationsInProgress.tsx
import React, { useState, useEffect } from "react"
import styled from "styled-components"
import axios from "axios"

import { FakeLinkExternal, CardItem } from "./SharedStyledComponents"
import Translation from "./Translation"

import { GATSBY_FUNCTIONS_PATH } from "../constants"

const LangContainer = styled.div`
  margin-bottom: 2rem;
  display: flex;
  flex-wrap: wrap;
`
const LangItem = styled(CardItem)`
  flex: 1 1 200px;
`

type LanguageType = {
  name: string
  code: string
  translated_progress: string
  approved_progress: string
}

export interface IProps {}

const TranslationsInProgress: React.FC<IProps> = () => {
  const [translationsInProgress, setTranslationsInProgress] = useState<
    LanguageType[]
  >([])

  useEffect(() => {
    axios
      .get(`${GATSBY_FUNCTIONS_PATH}/translations`)
      .then((response) => {
        let languages: LanguageType[] = []
        if (response.data && response.data.data) {
          languages = response.data.data
        }
        languages.sort((a, b) => a.name.localeCompare(b.name))
        setTranslationsInProgress(languages)
      })
      .catch((error) => {
        // TODO add toast message on fails
        console.error(error)
      })
  }, [])

  return (
    <LangContainer>
      {translationsInProgress.map((lang) => {
        const url = `https://crowdin.com/project/ethereum-org/${lang.code}`
        return (
          <LangItem to={url} key={lang.code} hideArrow>
            <h4>{lang.name}</h4>
            <div>
              <Translation id="translation-progress" />:{" "}
              {lang.translated_progress}%
            </div>
            <div>
              <Translation id="review-progress" />: {lang.approved_progress}%
            </div>
            <FakeLinkExternal>
              <Translation id="page-developers-contribute" />
            </FakeLinkExternal>
          </LangItem>
        )
      })}
    </LangContainer>
  )
}

export default TranslationsInProgress

// docs/.vuepress/components/TranslationsInProgress.vue
<template>
  <div>
    <div class="flex flex-wrap m-0 mt-2 mb-2">
      <a
        :href="lang.url"
        target="_blank"
        rel="noopener noreferrer"
        class="lang-item w-100 ma-1 pt-15 pb-15 pr-1 pl-1 border-box-shadow-hover hide-icon"
        v-for="lang in incomplete"
        :key="lang.code"
      >
        <h3 class="l4 tc-text500 mt-0 mb-05">{{ lang.name }}</h3>
        <p class="l5 tc-text400 ma-0">
          Translation progress: {{ lang.translated_progress }}%<br />
          Review progress: {{ lang.approved_progress }}%<br />
          <a
            :href="lang.url"
            target="_blank"
            rel="noopener noreferrer"
            class="block mt-05"
          >
            Contribute
          </a>
        </p>
      </a>
    </div>
  </div>
</template>

<script>
const axios = require('axios')

export default {
  data() {
    // TODO add loading & error states for this section
    // https://vuejs.org/v2/cookbook/using-axios-to-consume-apis.html
    return {
      incomplete: []
    }
  },

  mounted() {
    axios
      .get('/.netlify/functions/translations')
      .then(response => {
        let languages = []
        if (response.data && response.data.data) {
          languages = response.data.data
        }
        const incomplete = languages
          .map(lang => {
            lang.url = `https://crowdin.com/project/ethereumfoundation/${lang.code}`
            return lang
          })
          .sort((a, b) => a.name.localeCompare(b.name))
        this.incomplete = incomplete
      })
      // TODO create error case
      .catch(error => console.log(error))
  }
}
</script>

<style lang="stylus" scoped>
@import '../styles/config.styl';

.lang-item
  flex 0 1 260px
  list-style none
  border-radius .5rem
  width 100%

  & > h3:before
    display none

#wrapper.dark-mode
  .lang-item
    &:hover
      border 1px dotted $colorPrimaryDark500

@media (max-width: $breakXS)
  .lang-item
    margin 0
    margin-top 1rem
    flex 1 1 260px
</style>
