// docs/.vuepress/components/Footer.vue
<template>
  <footer class="footer flex flex-wrap space-between pt-3 pb-4" id="footer">
    <div class="flex flex-wrap space-between w-100 flex-center">
      <p class="flex flex-center l8 tc-text200">
        {{ lastUpdatedText }}: {{ lastUpdatedDate }}
      </p>
      <!-- Generate our social icons -->
      <ul class="social-links no-bullets pl-0 flex">
        <template v-for="(item, i) in socialLinks">
          <li :class="`social-link flex ma-0 ${i != 0 ? 'ml-05' : ''}`">
            <a
              :href="item.to"
              target="_blank"
              rel="noopener noreferrer"
              class="flex hide-icon"
              :aria-labelledby="item.icon + '-link'"
            >
              <icon :name="item.icon" size="36" />
            </a>
          </li>
        </template>
      </ul>
    </div>
    <!-- Generate link lists -->
    <div v-for="section in linkSections" class="list-block pr-2">
      <h3 class="l8 c-text500">
        <b>{{ section.title }}</b>
      </h3>
      <ul class="l8 ma-0 pl-0 no-bullets">
        <li v-if="link.display" class="mb-1" v-for="link in section.links">
          <a
            v-if="link.isExternal"
            :href="link.to"
            target="_blank"
            rel="noopener noreferrer"
            class="tc-text200 tc-h-primary500"
          >
            {{ link.text }}
          </a>

          <router-link v-else :to="link.to" class="tc-text200 tc-h-primary500">
            {{ link.text }}
          </router-link>
        </li>
      </ul>
    </div>
  </footer>
</template>

<script>
import moment from 'moment'
import { translate } from '../utils/translations'

export default {
  computed: {
    lastUpdatedDate() {
      const pagesSortedByDate = this.$site.pages.sort(
        (a, b) => b.lastUpdated - a.lastUpdated
      )
      moment.locale(this.$lang)
      return moment(pagesSortedByDate[0].lastUpdated).format('MMM DD, YYYY')
    },

    lastUpdatedText() {
      return translate('website-last-updated', this.$lang)
    },

    socialLinks() {
      return [
        {
          icon: 'github',
          to: 'https://github.com/ethereum'
        },
        {
          icon: 'twitter',
          to: 'https://twitter.com/ethereum'
        },
        {
          icon: 'youtube',
          to: 'https://youtube.com/channel/UCNOfzGXD_C9YMYmnefmPH0g'
        }
      ]
    },

    linkSections() {
      const contentVersion = translate('version', this.$lang)
      const langPath = translate('path', this.$lang)

      return [
        {
          title: translate('page-individuals', this.$lang),
          links: [
            {
              to: `${langPath}what-is-ethereum/`,
              text:
                contentVersion > 1
                  ? translate(
                      'page-home-section-individuals-item-one',
                      this.$lang
                    )
                  : translate(
                      'page-home-section-beginners-item-two',
                      this.$lang
                    ),
              display: true
            },
            {
              to: `${langPath}use/`,
              text: translate('page-use', this.$lang),
              display: contentVersion < 1.1
            },
            {
              to: `${langPath}eth/`,
              text: translate(
                'page-home-section-individuals-item-four',
                this.$lang
              ),
              display: contentVersion >= 1.1
            },
            {
              to: `${langPath}dapps/`,
              text: translate(
                'page-home-section-individuals-item-two',
                this.$lang
              ),
              display: contentVersion >= 1.1
            },
            {
              to: `${langPath}wallets/`,
              text: translate(
                'page-home-section-individuals-item-five',
                this.$lang
              ),
              display: contentVersion >= 1.1
            },
            {
              to: `${langPath}learn/`,
              text:
                contentVersion > 1
                  ? translate(
                      'page-home-section-individuals-item-three',
                      this.$lang
                    )
                  : translate('page-learn', this.$lang),
              display: true
            },
            {
              to: `${langPath}community/`,
              text: translate('page-community', this.$lang),
              display: contentVersion >= 1.2
            }
          ]
        },
        {
          title: translate('page-developers', this.$lang),
          links: [
            {
              to: `${langPath}build/`,
              text: translate('get-started', this.$lang),
              display: contentVersion >= 1.1
            },
            {
              to: 'https://studio.ethereum.org/',
              text: 'Ethereum Studio',
              isExternal: true,
              display: true
            },
            {
              to: `${langPath}developers/`,
              text:
                contentVersion > 1
                  ? translate('developer-resources', this.$lang)
                  : translate('page-developers', this.$lang),
              display: true
            },
            {
              to: '/whitepaper/',
              text: 'Ethereum Whitepaper',
              display: true
            }
          ]
        },
        {
          title: translate('footer-ecosystem', this.$lang),
          links: [
            {
              to: '/foundation/',
              text: 'Ethereum Foundation',
              display: true
            },
            {
              to: 'https://blog.ethereum.org/',
              text: 'Ethereum Foundation Blog',
              isExternal: true,
              display: true
            },
            {
              to: 'https://esp.ethereum.foundation',
              text: 'Ecosystem Support Program',
              isExternal: true,
              display: true
            },
            {
              to: '/eips/',
              text: 'Ethereum Improvement Proposals',
              display: true
            },
            {
              to: '/assets/',
              text: translate('ethereum-brand-assets', this.$lang),
              display: true
            },
            {
              to: 'https://devcon.org/',
              text: 'Devcon',
              isExternal: true,
              display: true
            }
          ]
        },
        {
          title: translate('footer-about', this.$lang),
          links: [
            {
              to: '/about/',
              text: 'About us',
              useRouter: true,
              display: true
            },
            {
              to: '/languages/',
              text: translate('language-support', this.$lang),
              display: true
            },
            {
              to: '/privacy-policy/',
              text: translate('privacy-policy', this.$lang),
              display: true
            },
            {
              to: '/terms-of-use/',
              text: translate('terms-of-use', this.$lang),
              display: true
            },
            {
              to: '/cookie-policy/',
              text: translate('cookie-policy', this.$lang),
              display: true
            },
            {
              to: 'mailto:press@ethereum.org',
              text: translate('contact', this.$lang),
              display: true,
              isExternal: true
            }
          ]
        }
      ]
    }
  }
}
</script>

<style lang="stylus">
@require '../styles/config';

footer
  width 85vw
  max-width $breakXL
  margin 0 auto
  .list-block
    min-width: 300px
    @media (min-width: $breakL)
      min-width initial

footer
  .social-links
    a
      svg path
        fill $subduedColor
      &:hover
        svg path
          fill $colorPrimary

.dark-mode footer
  .social-links
    a:hover
        svg path
          fill $colorPrimaryDark
</style>

// src/components/Footer.tsx
import {
  Box,
  Flex,
  Heading,
  Icon,
  List,
  ListItem,
  SimpleGrid,
  useToken,
} from "@chakra-ui/react"
import { graphql, useStaticQuery } from "gatsby"
import { useI18next, useTranslation } from "gatsby-plugin-react-i18next"
import React from "react"
import { FaDiscord, FaGithub, FaTwitter, FaYoutube } from "react-icons/fa"

import { Lang } from "../utils/languages"
import { getLocaleTimestamp } from "../utils/time"
import { isLangRightToLeft, TranslationKey } from "../utils/translations"
import { BaseLink } from "./Link"
import Translation from "./Translation"

const socialLinks = [
  {
    icon: FaGithub,
    to: "https://github.com/ethereum/ethereum-org-website",
    ariaLabel: "GitHub",
    color: "#333",
  },
  {
    icon: FaTwitter,
    to: "https://twitter.com/ethdotorg",
    ariaLabel: "Twitter",
    color: "#1DA1F2",
  },
  {
    icon: FaYoutube,
    to: "https://youtube.com/channel/UCNOfzGXD_C9YMYmnefmPH0g",
    ariaLabel: "Youtube",
    color: "#FF0000",
  },
  {
    icon: FaDiscord,
    to: "https://discord.gg/CetY6Y4",
    ariaLabel: "Discord",
    color: "#7289da",
  },
]
export interface LinkSection {
  title: TranslationKey
  links: Array<{
    to: string
    text: TranslationKey
    isPartiallyActive?: boolean
  }>
}

export interface IProps {}

const Footer: React.FC<IProps> = () => {
  const { language } = useI18next()
  const { t } = useTranslation()

  const isPageRightToLeft = isLangRightToLeft(language as Lang)

  const [medBp] = useToken("breakpoints", ["md"])

  const linkSections: Array<LinkSection> = [
    {
      title: t("use-ethereum"),
      links: [
        {
          to: "/wallets/find-wallet/",
          text: t("find-wallet"),
        },
        {
          to: `/get-eth/`,
          text: t("get-eth"),
        },
        {
          to: `/dapps/`,
          text: t("decentralized-applications-dapps"),
        },
        {
          to: "/layer-2/",
          text: t("layer-2"),
        },
        {
          to: "/run-a-node/",
          text: t("run-a-node"),
        },
        {
          to: `/stablecoins/`,
          text: t("stablecoins"),
        },
        {
          to: `/staking/`,
          text: t("stake-eth"),
        },
      ],
    },
    {
      title: t("learn"),
      links: [
        {
          to: `/learn/`,
          text: t("learn-hub"),
        },
        {
          to: `/what-is-ethereum/`,
          text: t("what-is-ethereum"),
        },
        {
          to: `/eth/`,
          text: t("what-is-ether"),
        },
        {
          to: `/wallets/`,
          text: t("ethereum-wallets"),
        },
        {
          to: "/security/",
          text: t("ethereum-security"),
        },
        {
          to: "/web3/",
          text: t("web3"),
        },
        {
          to: "/smart-contracts/",
          text: t("smart-contracts"),
        },
        {
          to: "/energy-consumption/",
          text: t("energy-consumption"),
        },
        {
          to: "/roadmap/",
          text: t("ethereum-roadmap"),
        },
        {
          to: "/eips/",
          text: t("eips"),
        },
        {
          to: "/history/",
          text: t("history-of-ethereum"),
        },
        {
          to: "/whitepaper/",
          text: t("ethereum-whitepaper"),
        },
        {
          to: `/glossary/`,
          text: t("ethereum-glossary"),
        },
        {
          to: "/governance/",
          text: t("ethereum-governance"),
        },
        {
          to: "/bridges/",
          text: t("bridges"),
        },
        {
          to: "/zero-knowledge-proofs/",
          text: t("zero-knowledge-proofs"),
        },
        {
          to: "/quizzes/",
          text: t("quizzes-title"),
        },
      ],
    },
    {
      title: t("developers"),
      links: [
        {
          to: `/developers/`,
          text: t("get-started"),
          isPartiallyActive: false,
        },
        {
          to: `/developers/docs/`,
          text: t("documentation"),
        },
        {
          to: `/developers/tutorials/`,
          text: t("tutorials"),
        },
        {
          to: `/developers/learning-tools/`,
          text: t("learn-by-coding"),
        },
        {
          to: `/developers/local-environment/`,
          text: t("set-up-local-env"),
        },
      ],
    },
    {
      title: t("ecosystem"),
      links: [
        {
          to: `/community/`,
          text: t("community-hub"),
        },
        {
          to: "/foundation/",
          text: t("ethereum-foundation"),
        },
        {
          to: "https://blog.ethereum.org/",
          text: t("ef-blog"),
        },
        {
          to: "https://esp.ethereum.foundation",
          text: t("esp"),
        },
        {
          to: "/bug-bounty/",
          text: t("ethereum-bug-bounty"),
        },
        {
          to: "/community/grants",
          text: t("grant-programs"),
        },
        {
          to: "/assets/",
          text: t("ethereum-brand-assets"),
        },
        {
          to: "https://devcon.org/",
          text: t("devcon"),
        },
      ],
    },
    {
      title: t("enterprise"),
      links: [
        {
          to: "/enterprise/",
          text: t("mainnet-ethereum"),
        },
        {
          to: "/enterprise/private-ethereum/",
          text: t("private-ethereum"),
        },
        {
          to: "/enterprise/",
          text: t("enterprise"),
        },
      ],
    },
    {
      title: t("about-ethereum-org"),
      links: [
        {
          to: "/about/",
          text: t("about-us"),
        },
        {
          to: "/about/#open-jobs",
          text: t("jobs"),
        },
        {
          to: "/contributing/",
          text: t("contributing"),
        },
        {
          to: "/languages/",
          text: t("language-support"),
        },
        {
          to: "/privacy-policy/",
          text: t("privacy-policy"),
        },
        {
          to: "/terms-of-use/",
          text: t("terms-of-use"),
        },
        {
          to: "/cookie-policy/",
          text: t("cookie-policy"),
        },
        {
          to: "mailto:press@ethereum.org",
          text: t("contact"),
        },
      ],
    },
  ]

  const data = useStaticQuery(graphql`
    query {
      allSiteBuildMetadata {
        edges {
          node {
            buildTime
          }
        }
      }
    }
  `)

  return (
    <Box as="footer" p="1rem 2rem">
      <Flex
        fontSize="sm"
        justify="space-between"
        alignItems="center"
        flexWrap="wrap"
      >
        <Box color="text200">
          <Translation id="website-last-updated" />:{" "}
          {getLocaleTimestamp(
            language as Lang,
            data.allSiteBuildMetadata.edges[0].node.buildTime
          )}
        </Box>
        <Box my={4}>
          {socialLinks.map((link, idk) => {
            return (
              <BaseLink
                key={idk}
                to={link.to}
                hideArrow
                color="secondary"
                aria-label={link.ariaLabel}
              >
                <Icon
                  as={link.icon}
                  _hover={{
                    color: link.color,
                    transition:
                      "color 0.2s ease-in-out, transform 0.2s ease-in-out",
                  }}
                  fontSize="4xl"
                  ml={4}
                />
              </BaseLink>
            )
          })}
        </Box>
      </Flex>
      <SimpleGrid
        gap={4}
        justifyContent="space-between"
        gridTemplateColumns="repeat(6, auto)"
        sx={{
          "@media (max-width: 1300px)": {
            gridTemplateColumns: "repeat(3, auto)",
          },
          [`@media (max-width: ${medBp})`]: {
            gridTemplateColumns: "repeat(2, auto)",
          },
          "@media (max-width: 500px)": {
            gridTemplateColumns: "auto",
          },
        }}
      >
        {linkSections.map((section: LinkSection, idx) => (
          <Box key={idx}>
            <Heading as="h3" fontSize="sm" lineHeight="1.6" my="1.14em">
              <Translation id={section.title} />
            </Heading>
            <List fontSize="sm" lineHeight="1.6" fontWeight="400" m={0}>
              {section.links.map((link, linkIdx) => (
                <ListItem key={linkIdx} mb={4}>
                  <BaseLink
                    to={link.to}
                    isPartiallyActive={false}
                    dir={isPageRightToLeft ? "auto" : "ltr"}
                    textDecor="none"
                    color="text200"
                    fontWeight="normal"
                    _hover={{
                      textDecor: "none",
                      color: "primary.base",
                      _after: {
                        color: "primary.base",
                      },
                      "& svg": {
                        fill: "primary.base",
                      },
                    }}
                    sx={{
                      "& svg": {
                        fill: "text200",
                      },
                    }}
                  >
                    {link.text}
                  </BaseLink>
                </ListItem>
              ))}
            </List>
          </Box>
        ))}
      </SimpleGrid>
    </Box>
  )
}

export default Footer
